// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sphkiyzwrecsyvhjnywt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwaGtpeXp3cmVjc3l2aGpueXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTIyNjgsImV4cCI6MjA3MjA4ODI2OH0.kFU1awk3RSrITLiFWHu7JslnCBq7RPCO26C3NYrQTu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});